// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(tintan) {
    var Tintan, build_deps;
    Tintan = tintan.constructor;
    build_deps = [];
    namespace('build', function() {
      if (Tintan.$.os === 'osx' && Tintan.appXML().targets('iphone')) {
        build_deps.push('build:iphone');
        desc('Build for iPhone');
        task('iphone', ['compile'], {
          async: true
        }, function() {
          return Tintan.$.tipy(['iphone', 'builder.py'], 'build', Tintan.$.ios_version(), process.cwd(), Tintan.appXML().id(), Tintan.appXML().name(), complete);
        });
      }
      if (Tintan.appXML().targets('android')) {
        build_deps.push('build:android');
        desc('Build for Android');
        return task('android', ['compile'], {
          async: true
        }, function() {
          return Tintan.$.tipy(['android', 'builder.py'], 'build', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), complete);
        });
      }
    });
    desc('Build sources');
    return task('build', build_deps);
  };

}).call(this);

/*
//@ sourceMappingURL=build.map
*/
