// Generated by CoffeeScript 1.6.3
(function() {
  var foundJavaHome, fs;

  fs = require('fs');

  foundJavaHome = function() {
    var java_home;
    java_home = process.env.JAVA_HOME;
    if (!(java_home && fs.existsSync(java_home))) {
      console.warn("Error: JAVA_HOME not set.  Will not be able to compile!");
      return;
    }
    return true;
  };

  module.exports = function(tintan) {
    var Tintan;
    Tintan = tintan.constructor;
    return namespace('distribute', function() {
      if (Tintan.appXML().targets('android')) {
        desc('Build final android distribution package for upload to marketplace');
        task('android', function() {
          var android_avd, conf;
          if (!foundJavaHome()) {
            return;
          }
          conf = Tintan.config();
          android_avd = process.env.AVD;
          android_avd || (android_avd = conf.envOrGet('android_avd'));
          return Tintan.$.tipy(['android', 'builder.py'], 'distribute', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), conf.envOrGet('keystore'), conf.envOrGet('storepass'), conf.envOrGet('key_alias'), Tintan.$._('./'), Tintan.$.android_version(), android_avd);
        });
      }
      if (Tintan.appXML().targets('ipad')) {
        desc('Build final ipad distribution package for upload to marketplace');
        task('ipad', function() {
          return Tintan.$.tipy(['iphone', 'builder.py'], 'distribute', Tintan.$.ios_version(), process.cwd(), Tintan.appXML().id(), Tintan.appXML().name(), 'ipad', 'retina');
        });
      }
      if (Tintan.appXML().targets('iphone')) {
        desc('Build final iphone distribution package for upload to marketplace');
        return task('iphone', function() {
          return Tintan.$.tipy(['iphone', 'builder.py'], 'distribute', Tintan.$.ios_version(), process.cwd(), Tintan.appXML().id(), Tintan.appXML().name(), 'iphone', 'retina');
        });
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=distribute.map
*/
