// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(tintan) {
    var Tintan, fastdev;
    Tintan = tintan.constructor;
    fastdev = Tintan.$.fastdev;
    if (Tintan.appXML().targets('android')) {
      return namespace('fastdev', function() {
        desc('Start fastdev server');
        task('start', function() {
          return fastdev('start');
        });
        desc('Stop fastdev server');
        task('stop', function() {
          return fastdev('stop');
        });
        desc('Get the status of the fastdev server');
        task('status', function() {
          return fastdev('status');
        });
        desc('Restart the app connected to this fastdev server');
        task('restart', function() {
          return fastdev('restart-app');
        });
        desc('Kill the app connected to this fastdev server');
        return task('kill', function() {
          return fastdev('kill-app');
        });
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=fastdev.map
*/
