// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(tintan) {
    var Tintan;
    Tintan = tintan.constructor;
    return namespace('install', function() {
      if (Tintan.appXML().targets('android')) {
        desc('Install the application on Android device');
        task('android', {
          async: true
        }, function() {
          var android_device, conf, debug_string;
          conf = Tintan.config();
          android_device = conf.envOrGet('android_device');
          if (conf.envOrGet('debug') === true) {
            debug_string = conf.envOrGet('debug_address') + ':' + conf.envOrGet('debug_port');
            return Tintan.$.tipy(['android', 'builder.py'], 'install', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), Tintan.$.android_version(), android_device, debug_string, complete);
          } else {
            return Tintan.$.tipy(['android', 'builder.py'], 'install', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), Tintan.$.android_version(), android_device, complete);
          }
        });
      }
      if (Tintan.$.os === 'osx') {
        if (Tintan.appXML().targets('ipad')) {
          desc('Install the application on iPad device');
          task('ipad', {
            async: true
          }, function() {
            return Tintan.$.tipy(['iphone', 'builder.py'], 'install', Tintan.$.ios_version(), process.cwd(), Tintan.appXML().id(), Tintan.appXML().name(), 'ipad', 'retina', complete);
          });
        }
        if (Tintan.appXML().targets('iphone')) {
          desc('Install the application on iPhone device');
          return task('iphone', {
            async: true
          }, function() {
            return Tintan.$.tipy(['iphone', 'builder.py'], 'install', Tintan.$.ios_version(), process.cwd(), Tintan.appXML().id(), Tintan.appXML().name(), 'iphone', 'retina', complete);
          });
        }
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=install.map
*/
