// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(tintan) {
    var Tintan;
    Tintan = tintan.constructor;
    return namespace('run', function() {
      if (Tintan.appXML().targets('android')) {
        desc('Run the Android emulator');
        task('emulator', function() {
          var android_avd;
          android_avd = process.env.AVD;
          android_avd || (android_avd = Tintan.config().envOrGet('android_avd'));
          return Tintan.$.tipy(['android', 'builder.py'], 'emulator', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), Tintan.$.android_version(), android_avd);
        });
      }
      if (Tintan.appXML().targets('android')) {
        desc('Run the application on Android emulator');
        task('android', function() {
          var android_avd, conf, debug_string;
          conf = Tintan.config();
          android_avd = process.env.AVD;
          android_avd || (android_avd = conf.envOrGet('android_avd'));
          if (conf.envOrGet('debug') === true) {
            debug_string = conf.envOrGet('debug_address') + ':' + conf.envOrGet('debug_port');
            return Tintan.$.tipy(['android', 'builder.py'], 'simulator', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), Tintan.$.android_version(), android_avd, debug_string);
          } else {
            return Tintan.$.tipy(['android', 'builder.py'], 'simulator', Tintan.appXML().name(), Tintan.$.android_home(), process.cwd(), Tintan.appXML().id(), Tintan.$.android_version(), android_avd);
          }
        });
      }
      if (Tintan.appXML().targets('ipad')) {
        desc('Run the application on iPad emulator');
        task('ipad', function() {
          return Tintan.$.tipy(['iphone', 'builder.py'], 'run', process.cwd(), Tintan.$.ios_version(), Tintan.appXML().id(), Tintan.appXML().name(), 'ipad');
        });
      }
      if (Tintan.appXML().targets('iphone')) {
        desc('Run the application on iPhone emulator');
        return task('iphone', function() {
          return Tintan.$.tipy(['iphone', 'builder.py'], 'run', process.cwd(), Tintan.$.ios_version(), Tintan.appXML().id(), Tintan.appXML().name(), 'iphone');
        });
      }
    });
  };

}).call(this);

/*
//@ sourceMappingURL=run.map
*/
