// Generated by CoffeeScript 1.6.3
(function() {
  var files;

  files = '\
\
  fastdev\
  compile\
  config\
  build\
  run\
  install\
  distribute\
\
'.trim().split(/[^a-zA-Z\/\.]+/).map(function(s) {
    return './' + s;
  });

  module.exports = function(tintan) {
    var file, _i, _len;
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      require(file)(tintan);
    }
    task('showenv', function() {
      return console.log(tintan.constructor.env);
    });
    return task('tintan', ['showenv', 'default'], function() {
      return console.log('done'.green + ' building ' + tintan.constructor.appXML().name());
    });
  };

}).call(this);

/*
//@ sourceMappingURL=tasks.map
*/
